### ISSUE TITLE
Would it make sense to automatically derive DevTools protocol types from a PDL file?

### ISSUE THREAD

**Issue by d4h0** [EverlastingBugstopper/chrome-devtools-rs#37]
Hi,

I'm wondering if you are aware that there is a definition of the DevTools protocol in the form of a PDL file ([see this page](https://github.com/ChromeDevTools/devtools-protocol/tree/master/pdl)).

There is even a crate that parses the file: [rust-pdl](https://crates.io/crates/pdl).

[This](https://github.com/flier/rust-chrome-devtools-protocol) is a repo of the rust-pdl developer that seems to demonstrate the usage of the library.

**Comment by EverlastingBugstopper** [comment]
that would make adding support for things much easier - it does seem like that other library already does that so making a clone of it doesn't entirely make sense. 

I created this crate to solve a very specific use case (parse console.log messages and display them in a terminal) and it's working so far for that.

I might set aside some time to look into PDL but for the time being I'm gonna leave things the way they are and if folks want a more robust protocol crate for more familiar use cases (manipulating the browser), they should probably look elsewhere in the ecosystem :)

Thanks for filing!

**Comment by d4h0** [comment]
Okay, thanks for the fast reply :)

**Comment by d4h0** [comment]
Just for completeness:

I just discovered that there is even a [JSON version](https://github.com/ChromeDevTools/devtools-protocol/tree/master/json) of the protocol definition. So the rust-pdl lib shouldn't even be needed.
